package com.qsoft.tictactoe.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.qsoft.tictactoe.ui.controller.ActionEventListener;

import javax.swing.*;
import java.awt.*;

/**
 * Created with IntelliJ IDEA.
 * User: khiemnt
 * Date: 8/16/13
 * Time: 8:39 AM
 * To change this template use File | Settings | File Templates.
 */
@org.springframework.stereotype.Component
public class MainGUI extends JFrame
{
    private JPanel panel1;
    private JButton bt0;
    private JButton bt6;
    private JButton bt1;
    private JButton bt4;
    private JButton bt7;
    private JButton bt2;
    private JButton bt5;
    private JButton bt8;
    private JButton btStart;
    private JButton btStop;
    private JLabel lbGameStatus;
    private JButton bt3;
    private JLabel lbGameResult;

    public void showUI()
    {
        $$$setupUI$$$();
        setContentPane(panel1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setName("TicTacToeGame");
        setSize(600, 600);
        setVisible(true);
    }

    //getter and setter


    public JButton getBtStart()
    {
        return btStart;
    }

    public JButton getBtStop()
    {
        return btStop;
    }

    public JLabel getLbGameStatus()
    {
        return lbGameStatus;
    }

    public void setLbGameStatus(JLabel lbGameStatus)
    {
        this.lbGameStatus = lbGameStatus;
    }

    public JLabel getLbGameResult()
    {
        return lbGameResult;
    }

    public void setLbGameResult(JLabel lbGameResult)
    {
        this.lbGameResult = lbGameResult;
    }

    public void addListener(ActionEventListener listener)
    {
        btStart.addActionListener(listener);
        btStop.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        lbGameStatus = new JLabel();
        lbGameStatus.setName("gameStatus");
        lbGameStatus.setText("");
        CellConstraints cc = new CellConstraints();
        panel1.add(lbGameStatus, cc.xy(1, 1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:57dlu:noGrow,fill:263px:noGrow,left:26dlu:noGrow,fill:max(d;4px):noGrow", "center:159px:noGrow"));
        panel1.add(panel2, cc.xy(1, 3));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel2.add(panel3, cc.xy(3, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        bt0 = new JButton();
        bt0.setLabel(" ");
        bt0.setName("0");
        bt0.setText(" ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt0, gbc);
        bt3 = new JButton();
        bt3.setLabel(" ");
        bt3.setName("3");
        bt3.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt3, gbc);
        bt6 = new JButton();
        bt6.setLabel(" ");
        bt6.setName("6");
        bt6.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt6, gbc);
        bt1 = new JButton();
        bt1.setName("1");
        bt1.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt1, gbc);
        bt4 = new JButton();
        bt4.setLabel(" ");
        bt4.setName("4");
        bt4.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt4, gbc);
        bt7 = new JButton();
        bt7.setActionCommand(" ");
        bt7.setLabel(" ");
        bt7.setName("7");
        bt7.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt7, gbc);
        bt2 = new JButton();
        bt2.setInheritsPopupMenu(false);
        bt2.setLabel(" ");
        bt2.setName("2");
        bt2.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt2, gbc);
        bt5 = new JButton();
        bt5.setName("5");
        bt5.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt5, gbc);
        bt8 = new JButton();
        bt8.setLabel(" ");
        bt8.setName("8");
        bt8.setText(" ");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bt8, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FormLayout("fill:72px:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel2.add(panel4, cc.xy(5, 1));
        btStart = new JButton();
        btStart.setLabel("Start");
        btStart.setName("btStart");
        btStart.setText("Start");
        panel4.add(btStart, cc.xy(1, 1));
        btStop = new JButton();
        btStop.setLabel("Stop");
        btStop.setName("btStop");
        btStop.setText("Stop");
        panel4.add(btStop, cc.xy(1, 3));
        lbGameResult = new JLabel();
        lbGameResult.setName("gameResult");
        lbGameResult.setText("");
        panel1.add(lbGameResult, cc.xy(1, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
